version: '3.9'

services:
  gateway-service:
    build: ./services/gateway-service
    container_name: gateway-service
    ports:
      - "3000:3000"
    env_file:
      - ./services/gateway-service/.env
    depends_on:
      - auth-service
      - user-service
    networks:
      - cosmix-net

  auth-service:
    build: ./services/auth-service
    container_name: auth-service
    env_file:
      - ./services/auth-service/.env
    depends_on:
      - db
      - rabbitmq
    networks:
      - cosmix-net

  user-service:
    build: ./services/user-service
    container_name: user-service
    env_file:
      - ./services/user-service/.env
    depends_on:
      - db
      - rabbitmq
    networks:
      - cosmix-net

  rabbitmq:
    image: rabbitmq:3-management
    container_name: cosmix-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - cosmix-net

  db:
    image: postgres:16
    container_name: cosmix-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      # POSTGRES_DB: cosmix_auth
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - cosmix-net

networks:
  cosmix-net:


volumes:
  pgdata:
