version: '3.9'

services:
  gateway-service:
    build: ./services/gateway-service
    container_name: gateway-service
    ports:
      - "5000:5000"
    env_file:
      - ./services/gateway-service/.env
    depends_on:
      - auth-service
      - user-service
    networks:
      - cosmix-net

  auth-service:
    build:
      context: .
      dockerfile: ./services/auth-service/Dockerfile
    container_name: auth-service
    env_file:
      - ./services/auth-service/.env
    depends_on:
      - db
      - rabbitmq
    networks:
      - cosmix-net

  user-service:
    build:
      context: .
      dockerfile: ./services/user-service/Dockerfile
    container_name: user-service
    env_file:
      - ./services/user-service/.env
    depends_on:
      - db
      - rabbitmq
    networks:
      - cosmix-net

  rabbitmq:
    image: rabbitmq:3-management
    container_name: cosmix-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - cosmix-net

  db:
    image: postgres:16
    container_name: cosmix-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - cosmix-net

  pgadmin:
    image: dpage/pgadmin4
    container_name: cosmix-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@cosmix.dev
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'True'
    ports:
      - "5050:80"
    volumes:
      - ./pgadmin/servers.json:/pgadmin4/servers.json
    depends_on:
      - db
    networks:
      - cosmix-net

networks:
  cosmix-net:


volumes:
  pgdata:
